### ISSUE TITLE
TODOs in switchboard/cpp/switchboard_pcie.hpp

### ISSUE THREAD

**Issue by sgherbst** [zeroasiccorp/switchboard#152]
Involves validating settings and adding a timeout.

https://github.com/zeroasiccorp/switchboard/blob/85484fa6a4ce4358a516d5639fa75807e007f5a1/switchboard/cpp/switchboard_pcie.hpp#L83

https://github.com/zeroasiccorp/switchboard/blob/85484fa6a4ce4358a516d5639fa75807e007f5a1/switchboard/cpp/switchboard_pcie.hpp#L96

**Comment by ObiWanRohan** [comment]
From the next lines, it appears as if the timeout is already present in a way. MAX_RETRIES along with the usleep is essentially a timeout. What is the idea for the timeout here?

https://github.com/zeroasiccorp/switchboard/blob/85484fa6a4ce4358a516d5639fa75807e007f5a1/switchboard/cpp/switchboard_pcie.hpp#L97-L103

Can you point to any resources/ideas about how to validate the version and ID?
https://github.com/zeroasiccorp/switchboard/blob/85484fa6a4ce4358a516d5639fa75807e007f5a1/switchboard/cpp/switchboard_pcie.hpp#L85-L89

**Comment by sgherbst** [comment]
Good catch - it looks like those TODO messages are out of date.  Will remove them.
